### ISSUE TITLE
Type warnings in customElement()

### ISSUE THREAD

**Issue by IParthJoshi** [isaaclyman/vue-custom-element-ts-example#1]
@isaaclyman  The demo is great and working as expected. I did updated the package to 2.0.4 and now the application runs well. But for some reason I am still getting type warnings as before in arguement of customElement(). Downloaded yours but there is no such warnings in that, its there in mine.
![custome_2 0 4](https://user-images.githubusercontent.com/28228669/35617452-43ce018e-0646-11e8-84f7-90b3c5c8f78d.JPG)
What do you think could be there I am missing ?

**Comment by isaaclyman** [comment]
@IParthJoshi If there's any way you could create a small repository that reproduces the issue, I'd be happy to take a look at it.

If, by chance, you're using Visual Studio Code, you should close and restart it, since the TypeScript plugin often doesn't update its cached types when NPM packages are updated.

**Comment by IParthJoshi** [comment]
@isaaclyman Thanks after restarting visual code it actually works! thanks.
